version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: overengineering-my-application-app
    ports:
      - 8080:8080
    networks:
      - overengineering-my-application-network
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    container_name: overengineering-my-application-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./metrics/prometheus/alerting.rules.yml:/etc/prometheus/alerting.rules.yml
      - prometheus-data:/prometheus
    networks:
      - overengineering-my-application-network
    command: 
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      alertmanager:
        condition: service_started
      grafana:
        condition: service_started
    
  alertmanager:
    image: prom/alertmanager
    container_name: overengineering-my-application-alertmanager
    ports:
    - "9093:9093"
    networks:
      - overengineering-my-application-network
    volumes:
      - "./metrics/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
      - alertmanager-data:/data
    command: 
      - --log.level=debug
      - --config.file=/etc/alertmanager/alertmanager.yml

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./metrics/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./metrics/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - overengineering-my-application-network

networks:
  overengineering-my-application-network:
    driver: bridge

volumes:
  prometheus-data:
  alertmanager-data:
