groups:
  - name: ServiceDown
    rules:
      - alert: InstanceDown 
        expr: up{job="services"} < 1 
        # change color
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

  # - name: Errors
  #   rules:
  #   - alert: HighErrorRate
  #     expr: job:request_errors:rate5m > 0.5
  #     for: 1s
  #     labels:
  #       severity: critical
  #     annotations:
  #       summary: "High error rate"
