// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/infrastructure/resilience/observable/observable.go

// Package mock_resilience is a generated GoMock package.
package mock_resilience

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockObserver) Notify(data interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notify", data)
}

// Notify indicates an expected call of Notify.
func (mr *MockObserverMockRecorder) Notify(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockObserver)(nil).Notify), data)
}
