name: Validate PR

on:
  push:
    branches:
      - feature**
      - bugfix**
      - hotfix**

jobs:
  # Reuse test workflow
  test:
    name: Test
    uses: ./.github/workflows/test.yaml